### ISSUE TITLE
v2.5.4 runtime failure – module name mismatch (hasown vs has-own)

### ISSUE THREAD

**Issue by gyhl** [form-data/form-data#583]
The latest patch release (v2.5.4) appears to break at runtime because of an incorrect module name in the new code introduced by commit 97ac9c208be0b83faeee04bb3faef1ed3474ee4c.

Problem summary
---------------  
* `lib/form_data.js` now contains `require('hasown')`. 
* `package.json` declares the dependency as `"has-own": "^1.0.0"`. 
* As a consequence, consumers receive:

```
Error: Cannot find module 'hasown'  
```

Reproduction
------------

```bash
mkdir form-data-test && cd form-data-test
npm init -y
npm i form-data@2.5.4 --install-strategy=nested   # install with hoisting disabled so only declared deps are present
node -e "require('form-data')"
```

Expected result  
---------------  
The module loads without throwing.

Actual result  
-------------  
Process exits immediately with `Error: Cannot find module 'hasown'`.

Thank you for looking into this! Let me know if any additional information is helpful.

**Comment by ljharb** [comment]
oops, thanks, fix incoming

**Comment by ljharb** [comment]
Fixed in 026abe5 and released in v2.5.5. Sorry about that!
